// This file was mostly generated by an LLM.

// Minimal helper that runs as user to capture OLE drops
// Outputs filename to stdout and exits

#include <Windows.h>
#include <ole2.h>
#include <Shlobj.h>
#include <iostream>
#include <string>

// Simplified drop target that just captures filename
class SimpleDropTarget : public IDropTarget {
    LONG m_refCount;
    std::string m_filename;

public:
    SimpleDropTarget() : m_refCount(1) {}

    STDMETHOD(QueryInterface)(REFIID iid, void** obj) {
        if (iid == IID_IDropTarget || iid == IID_IUnknown) {
            AddRef();
            *obj = this;
            return S_OK;
        }
        *obj = nullptr;
        return E_NOINTERFACE;
    }

    STDMETHOD_(ULONG, AddRef)() { return InterlockedIncrement(&m_refCount); }
    STDMETHOD_(ULONG, Release)() {
        LONG count = InterlockedDecrement(&m_refCount);
        if (count == 0) delete this;
        return count;
    }

    STDMETHOD(DragEnter)(IDataObject* dataObject, DWORD, POINTL, DWORD* effect) {
        *effect = DROPEFFECT_NONE;

        FORMATETC fmt = { CF_HDROP, 0, DVASPECT_CONTENT, -1, TYMED_HGLOBAL };
        STGMEDIUM stg;

        if (dataObject->GetData(&fmt, &stg) == S_OK) {
            PVOID data = GlobalLock(stg.hGlobal);
            wchar_t* wcData = (wchar_t*)((LPBYTE)data + sizeof(DROPFILES));

            std::cerr << "handling dragenter filename" << std::endl;

            char filename[MAX_PATH];
            wcstombs(filename, wcData, wcslen(wcData) + 1);
            m_filename = filename;

            GlobalUnlock(stg.hGlobal);
            ReleaseStgMedium(&stg);
        }
        return S_OK;
    }

    STDMETHOD(DragOver)(DWORD, POINTL, DWORD* effect) {
        *effect = DROPEFFECT_NONE;
        return S_OK;
    }

    STDMETHOD(DragLeave)() { return S_OK; }

    STDMETHOD(Drop)(IDataObject*, DWORD, POINTL, DWORD* effect) {
        *effect = DROPEFFECT_NONE;
        return S_OK;
    }

    const std::string& GetFilename() const { return m_filename; }
};

int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE, LPSTR lpCmdLine, int) {
    // Parse args: X Y SIZE
    int x = 0, y = 0, size = 20, timeout = 1000, testMode = 0;
    sscanf(lpCmdLine, "%d %d %d %d %d", &x, &y, &size, &timeout, &testMode);

    std::cerr << "Helper started: x=" << x << " y=" << y << " size=" << size << " timeout=" << timeout << " testMode=" << testMode << std::endl;

    POINT cursorPos;
    GetCursorPos(&cursorPos);
    std::cerr << "Cursor position: " << cursorPos.x << "," << cursorPos.y << std::endl;

    OleInitialize(nullptr);

    // Register window class
    WNDCLASSEX wc = {};
    wc.cbSize = sizeof(wc);
    wc.lpfnWndProc = DefWindowProc;
    wc.hInstance = hInstance;
    wc.lpszClassName = "InputLeapDropHelper";
    if (testMode) wc.hbrBackground = (HBRUSH)(COLOR_WINDOW + 1);
    RegisterClassEx(&wc);

    // Create drop window
    HWND hwnd = CreateWindowEx(
        WS_EX_TOPMOST | (testMode ? 0 : WS_EX_TRANSPARENT) | WS_EX_ACCEPTFILES,
        "InputLeapDropHelper", "",
        WS_POPUP,
        x, y, size, size,
        nullptr, nullptr, hInstance, nullptr);

    if (!hwnd) {
        std::cerr << "Failed to create window!" << std::endl;
        return 1;
    }

    // Register for drops
    SimpleDropTarget* dropTarget = new SimpleDropTarget();
    RegisterDragDrop(hwnd, dropTarget);

    ShowWindow(hwnd, SW_SHOW);
    std::cerr << "Window created and shown" << std::endl;

    // Process messages for timeout or until we get a filename
    DWORD startTime = GetTickCount();
    while (1) {
        if (GetTickCount() - startTime > (DWORD)timeout) {
            std::cerr << "Timed out." << std::endl;
            break;
        }
        MSG msg;
        while (PeekMessage(&msg, nullptr, 0, 0, PM_REMOVE)) {
            TranslateMessage(&msg);
            DispatchMessage(&msg);
        }

        if (!dropTarget->GetFilename().empty()) {
            std::cerr << "Got filename: " << dropTarget->GetFilename() << std::endl;
            break;
        }
        Sleep(10);
    }

    std::cerr << "Exiting. Filename: " << dropTarget->GetFilename() << std::endl;

    // Output filename to stdout (parent reads this)
    std::cout << dropTarget->GetFilename();

    RevokeDragDrop(hwnd);
    dropTarget->Release();
    DestroyWindow(hwnd);
    OleUninitialize();

    return 0;
}
