// This file was mostly generated by an LLM.

/*
 * InputLeap -- mouse and keyboard sharing utility
 * Copyright (C) 2026 InputLeap contributors
 *
 * This package is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * found in the file LICENSE that should have accompanied this file.
 *
 * This package is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#ifdef SYSAPI_WIN32

//TODO what is the proper solution?
#define WIN32_LEAN_AND_MEAN
#include <Windows.h>
#include <string>

namespace inputleap {

    // Enable a privilege for the current process
    bool enablePrivilege(const char* privilegeName);

    // Get the active console session ID
    DWORD getActiveConsoleSessionId();

    // Get user token from a session ID
    HANDLE getUserTokenFromSession(DWORD sessionId);

    // Get the interactive user's desktop path
    std::string getInteractiveUserDesktopPath();

    // RAII wrapper for Windows handles
    class ScopedHandle
    {
    public:
        explicit ScopedHandle(HANDLE h) : m_handle(h) {}

        ~ScopedHandle()
        {
            if (m_handle && m_handle != INVALID_HANDLE_VALUE) {
                CloseHandle(m_handle);
            }
        }

        HANDLE get() const { return m_handle; }
        operator bool() const { return m_handle && m_handle != INVALID_HANDLE_VALUE; }

    private:
        HANDLE m_handle;
        ScopedHandle(const ScopedHandle&) = delete;
        ScopedHandle& operator=(const ScopedHandle&) = delete;
    };

    // RAII wrapper for user impersonation
    class ScopedImpersonation
    {
    public:
        explicit ScopedImpersonation(HANDLE hToken);
        ~ScopedImpersonation();

        bool isActive() const { return m_active; }

    private:
        bool m_active;
        ScopedImpersonation(const ScopedImpersonation&) = delete;
        ScopedImpersonation& operator=(const ScopedImpersonation&) = delete;
    };

} // namespace inputleap

#endif // SYSAPI_WIN32
